/**
 *
 * This file is auto-generated. Do not edit manually: changes may be erased.
 * Generated by Aqua compiler: https://github.com/fluencelabs/aqua/.
 * If you find any bugs, please write an issue on GitHub: https://github.com/fluencelabs/aqua/issues
 * Aqua version: 0.7.5-342
 *
 */
import { Fluence, FluencePeer } from '@fluencelabs/fluence';
import {
    CallParams,
    callFunction,
    registerService,
} from '@fluencelabs/fluence/dist/internal/compilerSupport/v3';


// Services

export interface ICrossGameServiceDef {
    buyWeapon: (walletAddress: string, weapon: string, callParams: CallParams<'walletAddress' | 'weapon'>) => boolean | Promise<boolean>;
    getCurrentWeapon: (walletAddress: string, callParams: CallParams<'walletAddress'>) => string | Promise<string>;
    getInventory: (walletAddress: string, callParams: CallParams<'walletAddress'>) => { length: number; weapon: string[]; } | Promise<{ length: number; weapon: string[]; }>;
    readMetadata: (contractAddress: string, tokenId: string, callParams: CallParams<'contractAddress' | 'tokenId'>) => string | Promise<string>;
    registration: (walletAddress: string, callParams: CallParams<'walletAddress'>) => void | Promise<void>;
    updateCharacter: (walletAddress: string, weapon: string, callParams: CallParams<'walletAddress' | 'weapon'>) => void | Promise<void>;
}
export function registerICrossGameService(service: ICrossGameServiceDef): void;
export function registerICrossGameService(serviceId: string, service: ICrossGameServiceDef): void;
export function registerICrossGameService(peer: FluencePeer, service: ICrossGameServiceDef): void;
export function registerICrossGameService(peer: FluencePeer, serviceId: string, service: ICrossGameServiceDef): void;
       

export function registerICrossGameService(...args: any) {
    registerService(
        args,
        {
    "defaultServiceId" : "crossgameservice",
    "functions" : {
        "tag" : "labeledProduct",
        "fields" : {
            "buyWeapon" : {
                "tag" : "arrow",
                "domain" : {
                    "tag" : "labeledProduct",
                    "fields" : {
                        "walletAddress" : {
                            "tag" : "scalar",
                            "name" : "string"
                        },
                        "weapon" : {
                            "tag" : "scalar",
                            "name" : "string"
                        }
                    }
                },
                "codomain" : {
                    "tag" : "unlabeledProduct",
                    "items" : [
                        {
                            "tag" : "scalar",
                            "name" : "bool"
                        }
                    ]
                }
            },
            "getCurrentWeapon" : {
                "tag" : "arrow",
                "domain" : {
                    "tag" : "labeledProduct",
                    "fields" : {
                        "walletAddress" : {
                            "tag" : "scalar",
                            "name" : "string"
                        }
                    }
                },
                "codomain" : {
                    "tag" : "unlabeledProduct",
                    "items" : [
                        {
                            "tag" : "scalar",
                            "name" : "string"
                        }
                    ]
                }
            },
            "getInventory" : {
                "tag" : "arrow",
                "domain" : {
                    "tag" : "labeledProduct",
                    "fields" : {
                        "walletAddress" : {
                            "tag" : "scalar",
                            "name" : "string"
                        }
                    }
                },
                "codomain" : {
                    "tag" : "unlabeledProduct",
                    "items" : [
                        {
                            "tag" : "struct",
                            "name" : "Weapons",
                            "fields" : {
                                "length" : {
                                    "tag" : "scalar",
                                    "name" : "u32"
                                },
                                "weapon" : {
                                    "tag" : "array",
                                    "type" : {
                                        "tag" : "scalar",
                                        "name" : "string"
                                    }
                                }
                            }
                        }
                    ]
                }
            },
            "readMetadata" : {
                "tag" : "arrow",
                "domain" : {
                    "tag" : "labeledProduct",
                    "fields" : {
                        "contractAddress" : {
                            "tag" : "scalar",
                            "name" : "string"
                        },
                        "tokenId" : {
                            "tag" : "scalar",
                            "name" : "string"
                        }
                    }
                },
                "codomain" : {
                    "tag" : "unlabeledProduct",
                    "items" : [
                        {
                            "tag" : "scalar",
                            "name" : "string"
                        }
                    ]
                }
            },
            "registration" : {
                "tag" : "arrow",
                "domain" : {
                    "tag" : "labeledProduct",
                    "fields" : {
                        "walletAddress" : {
                            "tag" : "scalar",
                            "name" : "string"
                        }
                    }
                },
                "codomain" : {
                    "tag" : "nil"
                }
            },
            "updateCharacter" : {
                "tag" : "arrow",
                "domain" : {
                    "tag" : "labeledProduct",
                    "fields" : {
                        "walletAddress" : {
                            "tag" : "scalar",
                            "name" : "string"
                        },
                        "weapon" : {
                            "tag" : "scalar",
                            "name" : "string"
                        }
                    }
                },
                "codomain" : {
                    "tag" : "nil"
                }
            }
        }
    }
}
    );
}
      
// Functions

